# Coverage configuration
# ----------------------
coverage:
  range: 70..90     # First number represents red, and second represents green
  # (default is 70..100)
  round: down       # up, down, or nearest
  precision: 2      # Number of decimal places, between 0 and 5
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

# Ignoring Paths
# --------------
# which folders/files to ignore
ignore:
  - "web"         # ignore web folders
  - "proto"         # ignore web folders
  - "mock"        # ignore mock folders
  - "sql/grammar" # ignore sql grammar generate files
