// Generated by tmpl
// https://github.com/benbjohnson/tmpl
//
// DO NOT EDIT!
// Source: int_map_test.tmpl

package indexdb

import (
	"fmt"
	"testing"

	"github.com/lindb/roaring"
	"github.com/stretchr/testify/assert"
)

// hack test
func _assertForwardStoreData(t *testing.T, keys []uint32, m *ForwardStore) {
	for _, key := range keys {
		found, highIdx := m.keys.ContainsAndRankForHigh(key)
		assert.True(t, found)
		lowIdx := m.keys.RankForLow(key, highIdx-1)
		assert.True(t, found)
		assert.NotNil(t, m.values[highIdx-1][lowIdx-1])
	}
}

func TestForwardStore_Put(t *testing.T) {
	m := NewForwardStore()
	m.Put(1, 0)
	m.Put(8, 0)
	m.Put(3, 0)
	m.Put(5, 0)
	m.Put(6, 0)
	m.Put(7, 0)
	m.Put(4, 0)
	m.Put(2, 0)
	// test insert new high
	m.Put(2000000, 0)
	m.Put(2000001, 0)
	// test insert new high
	m.Put(200000, 0)

	_assertForwardStoreData(t, []uint32{1, 2, 3, 4, 5, 6, 7, 8, 200000, 2000000, 2000001}, m)
	assert.Equal(t, 11, m.Size())
	assert.Len(t, m.Values(), 3)

	err := m.WalkEntry(func(key uint32, value uint32) error {
		return fmt.Errorf("err")
	})
	assert.Error(t, err)

	keys := []uint32{1, 2, 3, 4, 5, 6, 7, 8, 200000, 2000000, 2000001}
	idx := 0
	err = m.WalkEntry(func(key uint32, value uint32) error {
		assert.Equal(t, keys[idx], key)
		idx++
		return nil
	})
	assert.NoError(t, err)
}

func TestForwardStore_Get(t *testing.T) {
	m := NewForwardStore()
	_, ok := m.Get(uint32(10))
	assert.False(t, ok)
	m.Put(1, 0)
	m.Put(8, 0)
	_, ok = m.Get(1)
	assert.True(t, ok)
	_, ok = m.Get(2)
	assert.False(t, ok)
	_, ok = m.Get(0)
	assert.False(t, ok)
	_, ok = m.Get(9)
	assert.False(t, ok)
	_, ok = m.Get(999999)
	assert.False(t, ok)
}

func TestForwardStore_Keys(t *testing.T) {
	m := NewForwardStore()
	m.Put(1, 0)
	m.Put(8, 0)
	assert.Equal(t, roaring.BitmapOf(1, 8), m.Keys())
}
